/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --config dist/server/wrangler.json` (hash: d5d839986022095265fcae9bba95235e)
interface __BaseEnv_Env {
  MEDIA: R2Bucket;
  DB: D1Database;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./dist/server/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
