/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --config dist/server/wrangler.json` (hash: d5d839986022095265fcae9bba95235e)
interface __BaseEnv_Env {
  MEDIA: R2Bucket;
  DB: D1Database;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  AUTH_ENCRYPTION_KEY: string;
  APP_ORIGIN?: string;
  GOOGLE_AUTH_URL?: string;
  GOOGLE_TOKEN_URL?: string;
  GOOGLE_JWKS_URL?: string;
  GOOGLE_REVOKE_URL?: string;
  YOUTUBE_API_BASE_URL?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./dist/server/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
