/**
 * The durable podcast model. Runtime queries intentionally use prepared D1
 * statements so the HTTP boundary stays explicit and easy to exercise.
 */
export const podcastSchema = {
  users: [
    'id',
    'google_sub',
    'email',
    'display_name',
    'created_at',
    'updated_at',
  ],
  oauth_states: [
    'state_hash',
    'code_verifier_ciphertext',
    'nonce',
    'expires_at',
    'created_at',
  ],
  youtube_connections: [
    'id',
    'user_id',
    'channel_id',
    'channel_title',
    'access_token_ciphertext',
    'refresh_token_ciphertext',
    'access_token_expires_at',
    'revoked_at',
    'created_at',
    'updated_at',
  ],
  sessions: [
    'id_hash',
    'user_id',
    'active_connection_id',
    'csrf_hash',
    'expires_at',
    'revoked_at',
    'created_at',
    'last_used_at',
  ],
  source_verifications: [
    'id',
    'user_id',
    'connection_id',
    'program_id',
    'video_id',
    'channel_id',
    'source_url',
    'verified_at',
    'expires_at',
    'status',
    'used_at',
  ],
  ownership_associations: [
    'id',
    'program_id',
    'user_id',
    'channel_id',
    'actor',
    'reason',
    'created_at',
  ],
  programs: [
    'id',
    'slug',
    'owner_user_id',
    'channel_id',
    'title',
    'description',
    'author',
    'language',
    'category',
    'explicit',
    'email',
    'cover_key',
    'cover_content_type',
    'created_at',
    'updated_at',
  ],
  episodes: [
    'guid',
    'program_id',
    'owner_user_id',
    'source_url',
    'source_video_id',
    'source_channel_id',
    'source_verification_id',
    'title',
    'description',
    'status',
    'audio_key',
    'audio_name',
    'mime_type',
    'size_bytes',
    'duration_seconds',
    'explicit',
    'episode_type',
    'season',
    'episode_number',
    'publish_at',
    'timezone',
    'published_at',
    'created_at',
    'updated_at',
    'audio_etag',
  ],
  destinations: [
    'program_id',
    'platform',
    'status',
    'public_url',
    'updated_at',
  ],
} as const;
